# Generated by Django 5.1.7 on 2025-03-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='news_image/default.jpeg', upload_to='news_image'),
        ),
    ]
